### ISSUE TITLE
Installing on ubuntu

### ISSUE THREAD

**Issue by savagesam93** [bancika/diy-layout-creator#420]
Can anyone give me tips on how to install diylc on ubuntu? Ive been trying for a little while and am having trouble.

**Comment by N9XYP** [comment]
I create a folder in my /home/michael folder called "diylc" and extract 
the contents of the downloads

I edit the run.sh file to this:  (please note I am on a 32-bit laptop 
that is really old)

    cd '/home/michael/diylc'
    java -splash:splash.png -Xms64m -Xmx256m -Dorg.diylc.scriptRun=true
    -Dfile.encoding=UTF-8 -cp diylc.jar:lib org.diylc.DIYLCStarter

to launch from the desktop I created this file called DIYLC and put it 
on the desktop

    [Desktop Entry]
    Version=1.0
    Type=Application
    Name=DIYLC
    Comment=
    Exec='/home/michael/diylc/run.sh'
    Icon=/home/michael/diylc/splash.png
    Path=
    Terminal=false
    StartupNotify=false

The splash screen shows up as a nice icon. Change michael to the name of 
your <user> folder obviously. I also deleted the Windows files.

Hope this helps

Michael

**Comment by savagesam93** [comment]
Tried what editing the run.sh file and when i run it i see the splash screen pop up briefly before getting this message

/home/rowsdower/diylc/run.sh: line 3: -Dfile.encoding=UTF-8: command not found

**Comment by noirimipsum** [comment]
first, make a copy of your run.sh file.

then replace the contents of the original to the below and see if it starts up for your or gives an error: 

java  -cp diylc.jar:lib org.diylc.DIYLCStarter

**Comment by johncala55** [comment]
I am having a similar issue, but I instead receive the error Could not find or load main class org.diylc.DIYLCSTARTER

Tried to edit run.sh as suggested in the previous comments.

**Comment by noirimipsum** [comment]
> I am having a similar issue, but I instead receive the error Could not find or load main class org.diylc.DIYLCSTARTER

this is a path error. you are using ubuntu or some linux type enviornment correct? assuming you placed in the Downloads directory from your home. open a command terminal and run the following commands (adjust for your directory location and the release version if needed).

cd Downloads
mkdir diy
cd diy 
unzip ../diylc-3.54.0.zip 
chmod 744 run.sh 
./run.sh       

if you get an error, type the following command in the terminal instead of ./run.sh. this should only be done for testing purposes.

java -cp diylc.jar:lib org.diylc.DIYLCStarter

if neither of these methods work, please post the errors.

**Comment by johncala55** [comment]
I've realized the error- I was downloading something called the diy-layout-creator-master (which, I'm guessing is the archive used for building?) rather than the plain ol' latest release archive, so run.sh was having an issue pointing to the correct path. Thanks for your assistance, all is working fine now.

**Comment by ChrisOfBristol** [comment]
I used to supply a Debian (.deb) package for DIYLC, this is a software package which is installed by a double-click on a Debian-based system. It was available on GetDeb which was an unofficial repository, but that appears to have changed hands and become unusable now. I have a deb for version 50 - if you want it just email me.

**Comment by joecool85** [comment]
I had the same " -Dfile.encoding=UTF-8: command not found" error.  I figured it out though and feel silly.  Lines two and three need to be one line.  IE, it should read like this:

cd '/home/michael/diylc'
java -splash:splash.png -Xms64m -Xmx256m -Dorg.diylc.scriptRun=true -Dfile.encoding=UTF-8 -cp diylc.jar:lib org.diylc.DIYLCStarter

**Comment by ChrisOfBristol** [comment]
I no longer support the Debian (.deb) package as Bancika now publishes a **Flatpak** which can be found [here](https://flathub.org/en-GB/apps/com.diy_fever.DIYLayoutCreator). Flatpaks can be installed on most Linux distributions, instructions are given on the webpage linked to above.
